/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml';
import { Route as AuthRouteImport } from './routes/auth';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin';
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
    id: '/sitemap.xml',
    path: '/sitemap.xml',
    getParentRoute: () => rootRouteImport,
});
const AuthRoute = AuthRouteImport.update({
    id: '/auth',
    path: '/auth',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
});
const AuthenticatedRouteRouteChildren = {
    AuthenticatedAdminRoute: AuthenticatedAdminRoute,
};
const AuthenticatedRouteRouteWithChildren = AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
    AuthRoute: AuthRoute,
    SitemapDotxmlRoute: SitemapDotxmlRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
